from __future__ import annotations

import json

from .projection import BuildRoomProjection


def render_data_js(projection: BuildRoomProjection) -> str:
    """Serialize the checked Python projection as the prototype's sole data artifact."""
    payload = json.dumps(projection.to_dict(), indent=2, ensure_ascii=False)
    return (
        "/* Generated by businessbuilder.build_room.serialization; never execution truth. */\n"
        f"window.BUILD_ROOM_PROJECTION = Object.freeze({payload});\n"
    )
