from __future__ import annotations

from typing import Protocol, Sequence

from .model import BrainRecord, Company, Dependency, InvalidationNotice, RecordKind, Scope


class CompanyBrainRepository(Protocol):
    """Storage port. Every method requires an explicit tenant/company scope."""

    def migrate(self) -> None: ...
    def close(self) -> None: ...
    def create_company(self, company: Company) -> Company: ...
    def get_company(self, scope: Scope) -> Company: ...
    def company_history(self, scope: Scope) -> list[Company]: ...
    def save_company(self, company: Company, *, expected_version: int) -> Company: ...
    def append_record(self, record: BrainRecord, *, expected_version: int | None) -> BrainRecord: ...
    def get_record(self, scope: Scope, record_id: str) -> BrainRecord: ...
    def list_current(self, scope: Scope, *, kinds: Sequence[RecordKind] | None = None) -> list[BrainRecord]: ...
    def history(self, scope: Scope, record_id: str | None = None) -> list[BrainRecord]: ...
    def add_dependency(self, dependency: Dependency) -> None: ...
    def dependencies_for(self, scope: Scope, source_record_id: str) -> list[Dependency]: ...
    def append_invalidation(self, notice: InvalidationNotice) -> None: ...
    def list_invalidations(self, scope: Scope) -> list[InvalidationNotice]: ...
