/* Generated by businessbuilder.build_room.serialization; never execution truth. */
window.BUILD_ROOM_PROJECTION = Object.freeze({
  "schema_version": "build-room.projection.v1",
  "generated_at": "2026-09-13T18:00:00Z",
  "source": {
    "mode": "offline_fixture",
    "fixture": "Billy Bob v1",
    "canonical": true,
    "mutable": false
  },
  "company": {
    "tenant_id": "tenant_billy",
    "company_id": "co_billy_bob_lawn",
    "display_name": "Billy Bob Lawn Care",
    "archetype": "Mobile service",
    "jurisdiction": "Denton County, Texas",
    "offer": "Recurring mow, edge & blow",
    "service_area": "12-mile radius",
    "lifecycle": "assembly"
  },
  "summary": {
    "total": 15,
    "complete": 10,
    "active": 2,
    "blocked": 1,
    "progress_percent": 67
  },
  "readiness": {
    "ready": false,
    "fully_set": false,
    "unmet_ready": [
      "website_deployed",
      "website_https",
      "ownership"
    ],
    "unmet_fully_set": [
      "monitoring",
      "handoff",
      "founder_buy_domain"
    ],
    "explanation": "The package is built, but Ready requires owned deployment and current customer-path evidence. Fully Set additionally requires monitoring and handoff."
  },
  "budget": {
    "currency": "USD",
    "ceiling_minor": 1000,
    "reserved_minor": 0,
    "settled_minor": 271,
    "available_minor": 729,
    "ceiling": "USD 10.00",
    "reserved": "USD 0.00",
    "settled": "USD 2.71",
    "available": "USD 7.29"
  },
  "work_items": [
    {
      "id": "job_bb_brain_001",
      "kind": "job",
      "title": "Lock the launch offer",
      "description": "Approve the narrow launch offer and its explicit exclusions.",
      "owner": "Business Builder",
      "status": "succeeded",
      "status_group": "done",
      "dependency_ids": [],
      "cost": "USD 0.00",
      "evidence_refs": [],
      "detail": "Chemicals, irrigation, tree work and hardscape remain outside launch scope."
    },
    {
      "id": "job_bb_website_001",
      "kind": "job",
      "title": "Build the customer website package",
      "description": "Create an accessible responsive package from approved Billy Bob facts.",
      "owner": "Website capability (offline fake)",
      "status": "succeeded",
      "status_group": "done",
      "dependency_ids": [
        "job_bb_brain_001"
      ],
      "cost": "USD 2.71",
      "evidence_refs": [
        "artifact:artifact_website_package"
      ],
      "detail": "Package ready is delivery evidence only. It does not mean deployed or live."
    },
    {
      "id": "verify_website_deployed",
      "kind": "verification",
      "title": "Production deployment",
      "description": "A deploy attempt exists; production ownership is not yet verified.",
      "owner": "Independent QA",
      "status": "executed",
      "status_group": "active",
      "dependency_ids": [
        "market_denton_12mi"
      ],
      "cost": "USD 0.00",
      "evidence_refs": [],
      "detail": "A deploy attempt exists; production ownership is not yet verified."
    },
    {
      "id": "verify_website_https",
      "kind": "verification",
      "title": "Secure HTTPS",
      "description": "TLS passed offline; current live evidence is still required.",
      "owner": "Independent QA",
      "status": "tested",
      "status_group": "active",
      "dependency_ids": [
        "market_denton_12mi"
      ],
      "cost": "USD 0.00",
      "evidence_refs": [
        "artifact:artifact_website_https_result"
      ],
      "detail": "TLS passed offline; current live evidence is still required."
    },
    {
      "id": "verify_website_links",
      "kind": "verification",
      "title": "Links and navigation",
      "description": "Required routes and links passed deterministic checks.",
      "owner": "Independent QA",
      "status": "verified",
      "status_group": "done",
      "dependency_ids": [
        "market_denton_12mi"
      ],
      "cost": "USD 0.00",
      "evidence_refs": [
        "artifact:artifact_website_links_result"
      ],
      "detail": "Required routes and links passed deterministic checks."
    },
    {
      "id": "verify_website_mobile",
      "kind": "verification",
      "title": "Mobile experience",
      "description": "Responsive behavior passed declared mobile checks.",
      "owner": "Independent QA",
      "status": "verified",
      "status_group": "done",
      "dependency_ids": [
        "market_denton_12mi"
      ],
      "cost": "USD 0.00",
      "evidence_refs": [
        "artifact:artifact_website_mobile_result"
      ],
      "detail": "Responsive behavior passed declared mobile checks."
    },
    {
      "id": "verify_website_forms",
      "kind": "verification",
      "title": "Customer contact form",
      "description": "Valid, invalid and out-of-radius lead cases passed.",
      "owner": "Independent QA",
      "status": "verified",
      "status_group": "done",
      "dependency_ids": [
        "market_denton_12mi"
      ],
      "cost": "USD 0.00",
      "evidence_refs": [
        "artifact:artifact_website_forms_result"
      ],
      "detail": "Valid, invalid and out-of-radius lead cases passed."
    },
    {
      "id": "verify_crm_lead_capture",
      "kind": "verification",
      "title": "Lead capture",
      "description": "Test leads were stored and traceable.",
      "owner": "Independent QA",
      "status": "verified",
      "status_group": "done",
      "dependency_ids": [],
      "cost": "USD 0.00",
      "evidence_refs": [
        "artifact:artifact_crm_lead_capture_result"
      ],
      "detail": "Test leads were stored and traceable."
    },
    {
      "id": "verify_workflow_quote",
      "kind": "verification",
      "title": "Quote path",
      "description": "Standard and exception quote fixtures passed.",
      "owner": "Independent QA",
      "status": "verified",
      "status_group": "done",
      "dependency_ids": [],
      "cost": "USD 0.00",
      "evidence_refs": [
        "artifact:artifact_workflow_quote_result"
      ],
      "detail": "Standard and exception quote fixtures passed."
    },
    {
      "id": "verify_scheduling_booking",
      "kind": "verification",
      "title": "Scheduling path",
      "description": "Capacity and conflict checks passed.",
      "owner": "Independent QA",
      "status": "verified",
      "status_group": "done",
      "dependency_ids": [],
      "cost": "USD 0.00",
      "evidence_refs": [
        "artifact:artifact_scheduling_booking_result"
      ],
      "detail": "Capacity and conflict checks passed."
    },
    {
      "id": "verify_email_inbound",
      "kind": "verification",
      "title": "Support inbox",
      "description": "Inbound support test reached the owned queue.",
      "owner": "Independent QA",
      "status": "verified",
      "status_group": "done",
      "dependency_ids": [],
      "cost": "USD 0.00",
      "evidence_refs": [
        "artifact:artifact_email_inbound_result"
      ],
      "detail": "Inbound support test reached the owned queue."
    },
    {
      "id": "verify_workflow_rollback",
      "kind": "verification",
      "title": "Rollback path",
      "description": "Failed release can be safely withdrawn.",
      "owner": "Independent QA",
      "status": "verified",
      "status_group": "done",
      "dependency_ids": [],
      "cost": "USD 0.00",
      "evidence_refs": [
        "artifact:artifact_workflow_rollback_result"
      ],
      "detail": "Failed release can be safely withdrawn."
    },
    {
      "id": "verify_monitoring_active",
      "kind": "verification",
      "title": "Launch monitoring",
      "description": "Monitoring requires a named owner before Fully Set.",
      "owner": "Independent QA",
      "status": "proposed",
      "status_group": "queued",
      "dependency_ids": [],
      "cost": "USD 0.00",
      "evidence_refs": [],
      "detail": "Monitoring requires a named owner before Fully Set."
    },
    {
      "id": "verify_handoff_complete",
      "kind": "verification",
      "title": "Customer handoff",
      "description": "Take the Keys has not yet been accepted.",
      "owner": "Independent QA",
      "status": "proposed",
      "status_group": "queued",
      "dependency_ids": [],
      "cost": "USD 0.00",
      "evidence_refs": [],
      "detail": "Take the Keys has not yet been accepted."
    },
    {
      "id": "job_bb_handoff_001",
      "kind": "job",
      "title": "Prepare Take the Keys handoff",
      "description": "Assemble the asset export ownership map evidence pack and runbook.",
      "owner": "Business Builder",
      "status": "waiting_founder",
      "status_group": "blocked",
      "dependency_ids": [
        "verify_handoff_complete",
        "founder_buy_domain"
      ],
      "cost": "USD 0.00",
      "evidence_refs": [],
      "detail": "Handoff stays locked until deployment evidence is current and founder-owned accounts are confirmed."
    }
  ],
  "approvals": [
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "approval_id": "approval_bb_launch_scope",
      "title": "Launch scope and exclusions",
      "summary": "12-mile mow, edge and blow offer; no regulated work.",
      "state": "granted",
      "subject_digest": "sha256:97cde3752632e90e07ad08153eabc4a9bcf196cf40a4d973ba9575a29b99c5ef",
      "subject_ref": "job:job_bb_website_001",
      "required_approver_role": "founder",
      "requested_at": "2026-09-13T17:52:00Z",
      "decided_at": "2026-09-13T17:54:00Z",
      "expires_at": null
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "approval_id": "approval_bb_publish",
      "title": "Publish website",
      "summary": "Publishing remains blocked until deployment ownership is proven.",
      "state": "requested",
      "subject_digest": "sha256:287046895bf78c8b0792ce4e6172523c641bf5a5134b87831e5b57f8743b88e7",
      "subject_ref": "job:job_bb_website_001",
      "required_approver_role": "founder",
      "requested_at": "2026-09-13T17:52:00Z",
      "decided_at": null,
      "expires_at": null
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "approval_id": "approval_bb_website_direction",
      "title": "Website direction",
      "summary": "Founder approved the customer-facing direction.",
      "state": "granted",
      "subject_digest": "sha256:d689c36ec8758a5e4cb747bc7b6a7b64c4a8a539e3b17c3f127e4072f8ad633c",
      "subject_ref": "job:job_bb_website_001",
      "required_approver_role": "founder",
      "requested_at": "2026-09-13T17:52:00Z",
      "decided_at": "2026-09-13T17:56:00Z",
      "expires_at": null
    }
  ],
  "evidence": [
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_crm_lead_capture_result",
      "title": "Crm Lead Capture",
      "evidence_type": "test_result",
      "artifact_ref": "artifact_crm_lead_capture_result",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "offline-independent-qa",
      "test_name": "crm-lead-capture",
      "test_passed": true
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_email_inbound_result",
      "title": "Email Inbound",
      "evidence_type": "test_result",
      "artifact_ref": "artifact_email_inbound_result",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "offline-independent-qa",
      "test_name": "email-inbound",
      "test_passed": true
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_scheduling_booking_result",
      "title": "Scheduling Booking",
      "evidence_type": "test_result",
      "artifact_ref": "artifact_scheduling_booking_result",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "offline-independent-qa",
      "test_name": "scheduling-booking",
      "test_passed": true
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_website_forms_result",
      "title": "Website Forms",
      "evidence_type": "test_result",
      "artifact_ref": "artifact_website_forms_result",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "offline-independent-qa",
      "test_name": "website-forms",
      "test_passed": true
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_website_https_result",
      "title": "Website Https",
      "evidence_type": "test_result",
      "artifact_ref": "artifact_website_https_result",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "offline-independent-qa",
      "test_name": "website-https",
      "test_passed": true
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_website_links_result",
      "title": "Website Links",
      "evidence_type": "test_result",
      "artifact_ref": "artifact_website_links_result",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "offline-independent-qa",
      "test_name": "website-links",
      "test_passed": true
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_website_mobile_result",
      "title": "Website Mobile",
      "evidence_type": "test_result",
      "artifact_ref": "artifact_website_mobile_result",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "offline-independent-qa",
      "test_name": "website-mobile",
      "test_passed": true
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_website_package",
      "title": "Website package artifact",
      "evidence_type": "audit_record",
      "artifact_ref": "artifact_website_package",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "fake.website.build",
      "test_name": null,
      "test_passed": null
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_workflow_quote_result",
      "title": "Workflow Quote",
      "evidence_type": "test_result",
      "artifact_ref": "artifact_workflow_quote_result",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "offline-independent-qa",
      "test_name": "workflow-quote",
      "test_passed": true
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "evidence_id": "evidence_workflow_rollback_result",
      "title": "Workflow Rollback",
      "evidence_type": "test_result",
      "artifact_ref": "artifact_workflow_rollback_result",
      "captured_at": "2026-09-13T18:00:00Z",
      "expires_at": null,
      "issuer": "offline-independent-qa",
      "test_name": "workflow-rollback",
      "test_passed": true
    }
  ],
  "founder_actions": [
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "founder_action_id": "founder_buy_domain",
      "title": "Buy the domain in your account",
      "reason": "Customer ownership and registrar evidence are required before launch.",
      "instructions": [
        "Purchase the approved domain in an account you control.",
        "Provide the receipt and ownership confirmation."
      ],
      "risk": "medium",
      "irreversible": true,
      "state": "required",
      "required_evidence_kinds": [
        "provider_receipt",
        "founder_attestation"
      ],
      "order": 1
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "founder_action_id": "founder_accept_handoff",
      "title": "Accept the Take the Keys handoff",
      "reason": "Confirms that assets, access and the runbook were received.",
      "instructions": [
        "Review the export and account map after deployment checks pass."
      ],
      "risk": "low",
      "irreversible": false,
      "state": "required",
      "required_evidence_kinds": [
        "founder_attestation"
      ],
      "order": 2
    }
  ],
  "blockers": [
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "blocker_id": "blocker_domain_ownership",
      "severity": "critical",
      "affected_target": "website.deployed",
      "reason": "The domain is not yet confirmed in Billy's registrar account.",
      "remediation": "Billy purchases the domain and supplies customer-owned account evidence.",
      "owner": "Billy Bob",
      "open": true
    },
    {
      "tenant_id": "tenant_billy",
      "company_id": "co_billy_bob_lawn",
      "blocker_id": "blocker_monitoring_owner",
      "severity": "noncritical",
      "affected_target": "monitoring.active",
      "reason": "A named monitoring owner has not been selected.",
      "remediation": "Assign an owner during handoff.",
      "owner": "Billy Bob",
      "open": true
    }
  ],
  "timeline": [
    {
      "event_id": "event_build_room_01",
      "event_type": "company.created",
      "label": "Company workspace created",
      "occurred_at": "2026-09-13T17:51:00Z",
      "sequence": 1,
      "detail": "Billy Bob Lawn Care entered assembly."
    },
    {
      "event_id": "event_build_room_02",
      "event_type": "decision.approved",
      "label": "Launch scope approved",
      "occurred_at": "2026-09-13T17:52:00Z",
      "sequence": 2,
      "detail": "The service area and exclusions were locked."
    },
    {
      "event_id": "event_build_room_03",
      "event_type": "job.requested",
      "label": "Website build queued",
      "occurred_at": "2026-09-13T17:53:00Z",
      "sequence": 3,
      "detail": "The website job was created with a bounded ceiling."
    },
    {
      "event_id": "event_build_room_04",
      "event_type": "founder.approved",
      "label": "Build approved",
      "occurred_at": "2026-09-13T17:54:00Z",
      "sequence": 4,
      "detail": "Billy approved the exact website job subject."
    },
    {
      "event_id": "event_build_room_05",
      "event_type": "job.started",
      "label": "Website build started",
      "occurred_at": "2026-09-13T17:55:00Z",
      "sequence": 5,
      "detail": "The offline fake began one bounded attempt."
    },
    {
      "event_id": "event_build_room_06",
      "event_type": "capability.progress",
      "label": "Website package reviewed",
      "occurred_at": "2026-09-13T17:56:00Z",
      "sequence": 6,
      "detail": "Research, build and review milestones completed."
    },
    {
      "event_id": "event_build_room_07",
      "event_type": "budget.settled",
      "label": "Build cost settled",
      "occurred_at": "2026-09-13T17:57:00Z",
      "sequence": 7,
      "detail": "$2.71 settled and the unused reservation was released."
    },
    {
      "event_id": "event_build_room_08",
      "event_type": "job.completed",
      "label": "Website package ready",
      "occurred_at": "2026-09-13T17:58:00Z",
      "sequence": 8,
      "detail": "Package artifact produced. Deployment is separate."
    },
    {
      "event_id": "event_build_room_09",
      "event_type": "verification.requested",
      "label": "Independent checks opened",
      "occurred_at": "2026-09-13T17:59:00Z",
      "sequence": 9,
      "detail": "Customer-path verification entered its evidence flow."
    }
  ],
  "handoff": {
    "state": "locked",
    "title": "Take the Keys",
    "description": "Your export, account map, evidence pack and operating runbook stay customer-owned.",
    "includes": [
      "Website package",
      "Brand and content assets",
      "Account ownership map",
      "Verification evidence",
      "Launch and rollback runbook"
    ],
    "blocked_by": [
      "founder_buy_domain",
      "website_deployed",
      "monitoring_active"
    ]
  }
});
